#pragma once

#include "../core/primitives.hpp"
#include "../core/traits.hpp"
#include "../core/memory.hpp"
#include "../core/allocator.hpp"
#include "../core/iterator.hpp"

namespace dsc {

// ── Array<T, Alloc> ───────────────────────────────────────────────────────────
// Cache-friendly dynamic array (resizable contiguous buffer).
//
// Performance highlights vs std::vector:
//   • Growth factor 1.5× — saves ~25 % peak memory vs 2× while keeping
//     O(1) amortized push_back (at most 1.5n total wasted capacity).
//   • memcpy / memmove fast-path for trivially copyable types; the compiler
//     optimises these into SIMD instructions automatically.
//   • emplace_back constructs in-place — no extra copies.
//   • insert() reallocation fuses move + insert in one pass (no double-move).

/// @brief Cache-friendly resizable contiguous-storage sequence container.
///
/// Stores elements in a single heap allocation. Provides O(1) amortised
/// push_back / emplace_back using a 1.5× growth factor and O(n) insert /
/// erase. Trivially copyable types receive memcpy / memmove fast-paths.
///
/// @tparam T     Element type. Must be move-constructible for reallocation.
/// @tparam Alloc Allocator type conforming to the dsc allocator interface.
///               Defaults to `Allocator<T>`.
template<typename T, typename Alloc = Allocator<T>>
class Array {
public:
    // ── Inner iterator ────────────────────────────────────────────────────────

    /// @brief Mutable random-access iterator over `Array<T, Alloc>` elements.
    ///
    /// Wraps a raw pointer and satisfies the `RandomAccessIterator` CRTP
    /// contract. Pointer arithmetic is delegated to `advance` and
    /// `distance_to` so that all standard iterator operators (+, -, +=, etc.)
    /// are generated by the base.
    struct Iterator : RandomAccessIterator<Iterator, T> {
        /// @brief Underlying raw pointer to the current element.
        T* p;

        /// @brief Constructs an iterator pointing to @p p.
        /// @param p Raw pointer to an element within the array's storage.
        explicit Iterator(T* p) noexcept : p(p) {}

        /// @brief Advances the iterator by @p n positions (may be negative).
        /// @param n Number of positions to advance; negative moves backward.
        /// @return Reference to `*this` after advancement.
        Iterator& advance(isize n)             noexcept { p += n; return *this; }

        /// @brief Dereferences the iterator to obtain the current element.
        /// @return Reference to the element at the current position.
        T&        deref()                const noexcept { return *p; }

        /// @brief Computes the signed distance from `*this` to @p o.
        /// @param o Another iterator within the same array.
        /// @return Signed element count between the two iterators.
        isize     distance_to(Iterator o) const noexcept { return o.p - p; }

        /// @brief Tests whether two iterators refer to the same position.
        /// @param o Iterator to compare with.
        /// @return `true` if both iterators point to the same element.
        bool      equal(Iterator o)       const noexcept { return p == o.p; }
    };

    /// @brief Immutable random-access iterator over `Array<T, Alloc>` elements.
    ///
    /// Identical to `Iterator` but yields `const T&` on dereference, allowing
    /// use over `const Array` instances.
    struct ConstIterator : RandomAccessIterator<ConstIterator, const T> {
        /// @brief Underlying raw pointer to the current (read-only) element.
        const T* p;

        /// @brief Constructs a const iterator pointing to @p p.
        /// @param p Raw pointer to a const element within the array's storage.
        explicit ConstIterator(const T* p) noexcept : p(p) {}

        /// @brief Advances the iterator by @p n positions (may be negative).
        /// @param n Number of positions to advance; negative moves backward.
        /// @return Reference to `*this` after advancement.
        ConstIterator& advance(isize n)                   noexcept { p += n; return *this; }

        /// @brief Dereferences the iterator to obtain the current element.
        /// @return Const reference to the element at the current position.
        const T&       deref()                      const noexcept { return *p; }

        /// @brief Computes the signed distance from `*this` to @p o.
        /// @param o Another const iterator within the same array.
        /// @return Signed element count between the two iterators.
        isize          distance_to(ConstIterator o) const noexcept { return o.p - p; }

        /// @brief Tests whether two const iterators refer to the same position.
        /// @param o Const iterator to compare with.
        /// @return `true` if both iterators point to the same element.
        bool           equal(ConstIterator o)       const noexcept { return p == o.p; }
    };

    /// @brief Type of the stored elements.
    using value_type      = T;
    /// @brief Mutable lvalue reference to an element.
    using reference       = T&;
    /// @brief Immutable lvalue reference to an element.
    using const_reference = const T&;
    /// @brief Mutable pointer to an element.
    using pointer         = T*;
    /// @brief Immutable pointer to an element.
    using const_pointer   = const T*;
    /// @brief Mutable iterator type (alias for `Iterator`).
    using iterator        = Iterator;
    /// @brief Immutable iterator type (alias for `ConstIterator`).
    using const_iterator  = ConstIterator;
    /// @brief Unsigned integral type used for sizes and indices.
    using size_type       = usize;

    // ── Construction ─────────────────────────────────────────────────────────

    /// @brief Default constructor. Creates an empty array with no allocation.
    /// @note `data()` returns `nullptr`, `size()` and `capacity()` are 0.
    /// @complexity O(1).
    Array() noexcept : data_(nullptr), size_(0), cap_(0) {}

    /// @brief Constructs an array of @p n default-initialised elements.
    /// @param n Number of elements to create.
    /// @note Each element is value-initialised via `Alloc::construct`.
    /// @complexity O(n).
    explicit Array(usize n) : size_(n), cap_(n) {
        data_ = Alloc::allocate(n);
        for (usize i = 0; i < n; ++i) Alloc::construct(data_ + i);
    }

    /// @brief Constructs an array of @p n copies of @p val.
    /// @param n   Number of elements to create.
    /// @param val Value used to copy-initialise every element.
    /// @complexity O(n).
    Array(usize n, const T& val) : size_(n), cap_(n) {
        data_ = Alloc::allocate(n);
        for (usize i = 0; i < n; ++i) Alloc::construct(data_ + i, val);
    }

    /// @brief Copy constructor. Deep-copies all elements from @p o.
    /// @param o Source array to copy from.
    /// @note Capacity of the new array equals `o.size()` (no excess reserved).
    /// @complexity O(n).
    Array(const Array& o) : size_(o.size_), cap_(o.size_) {
        data_ = Alloc::allocate(cap_);
        copy_construct_range(data_, o.data_, size_);
    }

    /// @brief Move constructor. Transfers ownership from @p o.
    /// @param o Source array to move from. Left empty after the operation.
    /// @complexity O(1).
    Array(Array&& o) noexcept : data_(o.data_), size_(o.size_), cap_(o.cap_) {
        o.data_ = nullptr; o.size_ = o.cap_ = 0;
    }

    /// @brief Destructor. Destroys all elements and releases the allocation.
    /// @complexity O(n) for non-trivially destructible `T`; O(1) otherwise.
    ~Array() { clear(); Alloc::deallocate(data_, cap_); }

    /// @brief Copy-assignment operator. Replaces the contents with a copy of @p o.
    /// @param o Source array to copy from.
    /// @return Reference to `*this`.
    /// @note Reuses the existing allocation if it is large enough.
    /// @complexity O(n).
    Array& operator=(const Array& o) {
        if (this != &o) {
            clear();
            if (cap_ < o.size_) { Alloc::deallocate(data_, cap_); cap_ = o.size_; data_ = Alloc::allocate(cap_); }
            size_ = o.size_;
            copy_construct_range(data_, o.data_, size_);
        }
        return *this;
    }

    /// @brief Move-assignment operator. Transfers ownership from @p o.
    /// @param o Source array to move from. Left empty after the operation.
    /// @return Reference to `*this`.
    /// @complexity O(n) to destroy current elements; O(1) for the transfer.
    Array& operator=(Array&& o) noexcept {
        if (this != &o) {
            clear(); Alloc::deallocate(data_, cap_);
            data_ = o.data_; size_ = o.size_; cap_ = o.cap_;
            o.data_ = nullptr; o.size_ = o.cap_ = 0;
        }
        return *this;
    }

    // ── Capacity ──────────────────────────────────────────────────────────────

    /// @brief Returns the number of elements currently stored.
    /// @return Current element count.
    /// @complexity O(1).
    [[nodiscard]] usize size()     const noexcept { return size_; }

    /// @brief Returns the number of elements that can be stored without reallocation.
    /// @return Current allocated capacity.
    /// @complexity O(1).
    [[nodiscard]] usize capacity() const noexcept { return cap_; }

    /// @brief Returns `true` if the array contains no elements.
    /// @return `true` when `size() == 0`.
    /// @complexity O(1).
    [[nodiscard]] bool  empty()    const noexcept { return size_ == 0; }

    /// @brief Ensures the array can hold at least @p n elements without reallocation.
    /// @param n Desired minimum capacity.
    /// @note Has no effect if `n <= capacity()`.
    /// @complexity O(n) if reallocation occurs; O(1) otherwise.
    void reserve(usize n) { if (n > cap_) reallocate(n); }

    /// @brief Releases excess capacity so that `capacity() == size()`.
    /// @note May be a no-op if the array is already at exact capacity.
    /// @complexity O(n) if reallocation occurs; O(1) otherwise.
    void shrink_to_fit() { if (size_ < cap_) reallocate(size_); }

    // ── Element access ────────────────────────────────────────────────────────

    /// @brief Unchecked element access by index (mutable).
    /// @param i Zero-based index of the element.
    /// @return Mutable reference to the element at position @p i.
    /// @pre `i < size()`; no bounds checking is performed.
    /// @complexity O(1).
    reference       operator[](usize i)       noexcept { return data_[i]; }

    /// @brief Unchecked element access by index (const).
    /// @param i Zero-based index of the element.
    /// @return Const reference to the element at position @p i.
    /// @pre `i < size()`; no bounds checking is performed.
    /// @complexity O(1).
    const_reference operator[](usize i) const noexcept { return data_[i]; }

    /// @brief Returns a mutable reference to the first element.
    /// @return Reference to `data()[0]`.
    /// @pre `!empty()`.
    /// @complexity O(1).
    reference       front()                   noexcept { return data_[0]; }

    /// @brief Returns a const reference to the first element.
    /// @return Const reference to `data()[0]`.
    /// @pre `!empty()`.
    /// @complexity O(1).
    const_reference front()             const noexcept { return data_[0]; }

    /// @brief Returns a mutable reference to the last element.
    /// @return Reference to `data()[size() - 1]`.
    /// @pre `!empty()`.
    /// @complexity O(1).
    reference       back()                    noexcept { return data_[size_ - 1]; }

    /// @brief Returns a const reference to the last element.
    /// @return Const reference to `data()[size() - 1]`.
    /// @pre `!empty()`.
    /// @complexity O(1).
    const_reference back()              const noexcept { return data_[size_ - 1]; }

    /// @brief Returns a pointer to the underlying contiguous storage (mutable).
    /// @return Pointer to the first element, or `nullptr` if `capacity() == 0`.
    /// @complexity O(1).
    pointer         data()                    noexcept { return data_; }

    /// @brief Returns a pointer to the underlying contiguous storage (const).
    /// @return Const pointer to the first element, or `nullptr` if `capacity() == 0`.
    /// @complexity O(1).
    const_pointer   data()              const noexcept { return data_; }

    // ── Modifiers ─────────────────────────────────────────────────────────────

    /// @brief Appends a copy of @p v to the end of the array.
    /// @param v Value to copy-append.
    /// @note Triggers a 1.5× reallocation if `size() == capacity()`.
    /// @complexity O(1) amortised.
    void push_back(const T& v) { if (size_ == cap_) grow(); Alloc::construct(data_ + size_++, v); }

    /// @brief Appends @p v to the end of the array by move.
    /// @param v Value to move-append.
    /// @note Triggers a 1.5× reallocation if `size() == capacity()`.
    /// @complexity O(1) amortised.
    void push_back(T&& v)      { if (size_ == cap_) grow(); Alloc::construct(data_ + size_++, traits::move(v)); }

    /// @brief Constructs a new element in-place at the end of the array.
    /// @tparam Args Constructor argument types forwarded to `T`'s constructor.
    /// @param  args Arguments forwarded to the constructor of `T`.
    /// @return Mutable reference to the newly constructed element.
    /// @note Triggers a 1.5× reallocation if `size() == capacity()`.
    /// @complexity O(1) amortised.
    template<typename... Args>
    T& emplace_back(Args&&... args) {
        if (size_ == cap_) grow();
        Alloc::construct(data_ + size_, traits::forward<Args>(args)...);
        return data_[size_++];
    }

    /// @brief Removes the last element.
    /// @note Has no effect if the array is empty.
    /// @complexity O(1).
    void pop_back() noexcept { if (size_ > 0) Alloc::destroy(data_ + --size_); }

    // Insert before pos

    /// @brief Inserts a copy of @p v before @p pos.
    /// @param pos Iterator to the position before which to insert.
    /// @param v   Value to copy-insert.
    /// @return Iterator pointing to the newly inserted element.
    /// @note If `size() == capacity()`, a fused reallocation-plus-insert is
    ///       performed in a single pass (no double-move of existing elements).
    /// @complexity O(n) due to element shifting.
    Iterator insert(Iterator pos, const T& v)  { return insert_at(pos.p - data_, v); }

    /// @brief Inserts @p v before @p pos by move.
    /// @param pos Iterator to the position before which to insert.
    /// @param v   Value to move-insert.
    /// @return Iterator pointing to the newly inserted element.
    /// @note If `size() == capacity()`, a fused reallocation-plus-insert is
    ///       performed in a single pass.
    /// @complexity O(n) due to element shifting.
    Iterator insert(Iterator pos, T&& v)        { return insert_at(pos.p - data_, traits::move(v)); }

    // Erase single element

    /// @brief Removes the element at @p pos.
    /// @param pos Iterator to the element to remove.
    /// @return Iterator to the element that followed @p pos, or `end()` if
    ///         @p pos was the last element.
    /// @pre `pos` must be a valid dereferenceable iterator into this array.
    /// @complexity O(n) due to shifting subsequent elements left.
    Iterator erase(Iterator pos) noexcept {
        usize i = static_cast<usize>(pos.p - data_);
        Alloc::destroy(data_ + i);
        shift_left(data_ + i, size_ - i - 1);
        --size_;
        return Iterator(data_ + i);
    }

    // Erase range [first, last)

    /// @brief Removes all elements in the half-open range `[first, last)`.
    /// @param first Iterator to the first element to remove.
    /// @param last  Iterator one past the last element to remove.
    /// @return Iterator to the element that followed the last removed element,
    ///         or `end()` if the range extended to the end.
    /// @pre `first` and `last` must be valid iterators into this array with
    ///      `first <= last`.
    /// @complexity O(n).
    Iterator erase(Iterator first, Iterator last) noexcept {
        usize f = static_cast<usize>(first.p - data_);
        usize l = static_cast<usize>(last.p  - data_);
        for (usize i = f; i < l; ++i) Alloc::destroy(data_ + i);
        usize n = l - f;
        shift_left(data_ + f, size_ - l);
        size_ -= n;
        return Iterator(data_ + f);
    }

    /// @brief Resizes the array to contain exactly @p n default-initialised elements.
    ///
    /// If @p n is greater than the current size, new elements are
    /// value-initialised. If @p n is smaller, excess elements are destroyed.
    /// @param n Target size.
    /// @complexity O(n).
    void resize(usize n) {
        if (n > size_) { reserve(n); for (usize i = size_; i < n; ++i) Alloc::construct(data_ + i); }
        else           { for (usize i = n; i < size_; ++i) Alloc::destroy(data_ + i); }
        size_ = n;
    }

    /// @brief Resizes the array, filling new elements with copies of @p val.
    ///
    /// If @p n is greater than the current size, new elements are copy-
    /// constructed from @p val. If @p n is smaller, excess elements are
    /// destroyed.
    /// @param n   Target size.
    /// @param val Value used to initialise any new elements.
    /// @complexity O(n).
    void resize(usize n, const T& val) {
        if (n > size_) { reserve(n); for (usize i = size_; i < n; ++i) Alloc::construct(data_ + i, val); }
        else           { for (usize i = n; i < size_; ++i) Alloc::destroy(data_ + i); }
        size_ = n;
    }

    /// @brief Destroys all elements, leaving `size() == 0`.
    /// @note The allocated buffer is retained; call `shrink_to_fit()` to
    ///       release it.
    /// @complexity O(n) for non-trivially destructible `T`; O(1) otherwise.
    void clear() noexcept {
        if constexpr (!traits::is_trivially_destructible_v<T>)
            for (usize i = 0; i < size_; ++i) Alloc::destroy(data_ + i);
        size_ = 0;
    }

    // ── Search ────────────────────────────────────────────────────────────────

    /// @brief Returns the index of the first element equal to @p v.
    /// @tparam U Type comparable to `T` via `operator==`.
    /// @param  v Value to search for.
    /// @return Zero-based index of the first matching element, or `-1` if
    ///         not found.
    /// @complexity O(n).
    template<typename U>
    [[nodiscard]] isize index_of(const U& v) const noexcept {
        for (usize i = 0; i < size_; ++i) if (data_[i] == v) return static_cast<isize>(i);
        return -1;
    }

    /// @brief Tests whether any element equals @p v.
    /// @tparam U Type comparable to `T` via `operator==`.
    /// @param  v Value to search for.
    /// @return `true` if at least one element compares equal to @p v.
    /// @complexity O(n).
    template<typename U>
    [[nodiscard]] bool contains(const U& v) const noexcept { return index_of(v) >= 0; }

    // ── Iterators ─────────────────────────────────────────────────────────────

    /// @brief Returns a mutable iterator to the first element.
    /// @return `Iterator` pointing to `data()[0]`, or `end()` if empty.
    /// @complexity O(1).
    Iterator      begin()        noexcept { return Iterator(data_); }

    /// @brief Returns a mutable iterator one past the last element.
    /// @return `Iterator` pointing to `data()[size()]`.
    /// @complexity O(1).
    Iterator      end()          noexcept { return Iterator(data_ + size_); }

    /// @brief Returns a const iterator to the first element.
    /// @return `ConstIterator` pointing to `data()[0]`, or `cend()` if empty.
    /// @complexity O(1).
    ConstIterator begin()  const noexcept { return ConstIterator(data_); }

    /// @brief Returns a const iterator one past the last element.
    /// @return `ConstIterator` pointing to `data()[size()]`.
    /// @complexity O(1).
    ConstIterator end()    const noexcept { return ConstIterator(data_ + size_); }

    /// @brief Returns a const iterator to the first element (explicit const).
    /// @return Same as `begin() const`.
    /// @complexity O(1).
    ConstIterator cbegin() const noexcept { return begin(); }

    /// @brief Returns a const iterator one past the last element (explicit const).
    /// @return Same as `end() const`.
    /// @complexity O(1).
    ConstIterator cend()   const noexcept { return end(); }

    // ── Comparison ────────────────────────────────────────────────────────────

    /// @brief Element-wise equality comparison.
    /// @param o Array to compare with.
    /// @return `true` if both arrays have the same size and all corresponding
    ///         elements compare equal via `operator==`.
    /// @complexity O(n).
    bool operator==(const Array& o) const noexcept {
        if (size_ != o.size_) return false;
        for (usize i = 0; i < size_; ++i) if (!(data_[i] == o.data_[i])) return false;
        return true;
    }

    /// @brief Element-wise inequality comparison.
    /// @param o Array to compare with.
    /// @return `true` if `!(*this == o)`.
    /// @complexity O(n).
    bool operator!=(const Array& o) const noexcept { return !(*this == o); }

private:
    T*    data_;
    usize size_;
    usize cap_;

    // 1.5× growth, minimum capacity 4

    /// @brief Grows the buffer using the 1.5× policy (minimum capacity 4).
    /// @note Called automatically when `size_ == cap_` before an insertion.
    /// @complexity O(n).
    void grow() { reallocate(cap_ == 0 ? 4 : cap_ + (cap_ >> 1)); }

    /// @brief Reallocates the internal buffer to hold exactly @p new_cap elements.
    ///
    /// Existing elements are move-constructed into the new buffer and the old
    /// buffer is released.
    /// @param new_cap New capacity; must be >= `size_`.
    /// @complexity O(n).
    void reallocate(usize new_cap) {
        T* nd = Alloc::allocate(new_cap);
        if (data_) {
            move_construct_range(nd, data_, size_);
            Alloc::deallocate(data_, cap_);
        }
        data_ = nd; cap_ = new_cap;
    }

    /// @brief Copy-constructs @p n elements from @p src into uninitialised @p dst.
    ///
    /// Uses `mem::copy` for trivially copyable types; falls back to
    /// per-element `Alloc::construct` otherwise.
    /// @param dst Pointer to uninitialised destination storage.
    /// @param src Pointer to source elements.
    /// @param n   Number of elements to copy.
    /// @complexity O(n).
    static void copy_construct_range(T* dst, const T* src, usize n) noexcept {
        if constexpr (traits::is_trivially_copyable_v<T>) {
            mem::copy(dst, src, n * sizeof(T));
        } else {
            for (usize i = 0; i < n; ++i) Alloc::construct(dst + i, src[i]);
        }
    }

    /// @brief Move-constructs @p n elements from @p src into uninitialised @p dst
    ///        and destroys the source elements.
    ///
    /// Uses `mem::copy` for trivially copyable types (no explicit destruction
    /// needed); otherwise move-constructs and destroys each element.
    /// @param dst Pointer to uninitialised destination storage.
    /// @param src Pointer to source elements (destroyed after the operation).
    /// @param n   Number of elements to move.
    /// @complexity O(n).
    static void move_construct_range(T* dst, T* src, usize n) noexcept {
        if constexpr (traits::is_trivially_copyable_v<T>) {
            mem::copy(dst, src, n * sizeof(T));
        } else {
            for (usize i = 0; i < n; ++i) {
                Alloc::construct(dst + i, traits::move(src[i]));
                Alloc::destroy(src + i);
            }
        }
    }

    /// @brief Shifts @p n elements starting at @p base one position to the left.
    ///
    /// Equivalent to moving elements at `[base+1 .. base+n]` into `[base .. base+n-1]`.
    /// Uses `mem::move_bytes` for trivially copyable types.
    /// @param base Pointer to the element that will be overwritten.
    /// @param n    Number of elements to shift.
    /// @complexity O(n).
    static void shift_left(T* base, usize n) noexcept {
        if constexpr (traits::is_trivially_copyable_v<T>) {
            mem::move_bytes(base, base + 1, n * sizeof(T));
        } else {
            for (usize i = 0; i < n; ++i) base[i] = traits::move(base[i + 1]);
        }
    }

    /// @brief Shifts @p n elements starting at @p base one position to the right.
    ///
    /// Equivalent to moving elements at `[base .. base+n-1]` into `[base+1 .. base+n]`.
    /// The slot at @p base is left in a valid-but-unspecified state.
    /// Uses `mem::move_bytes` for trivially copyable types.
    /// @param base Pointer to the first element to shift.
    /// @param n    Number of elements to shift.
    /// @complexity O(n).
    static void shift_right(T* base, usize n) noexcept {
        if constexpr (traits::is_trivially_copyable_v<T>) {
            mem::move_bytes(base + 1, base, n * sizeof(T));
        } else {
            for (usize i = n; i-- > 0;) base[i + 1] = traits::move(base[i]);
        }
    }

    /// @brief Inserts a forwarded value at index @p idx, growing if necessary.
    ///
    /// If a reallocation is required, the new element and all existing elements
    /// are placed into the new buffer in a single pass (fused insert).
    /// Otherwise, existing elements at `[idx, size_)` are shifted right by one
    /// and the new element is constructed at @p idx.
    ///
    /// @tparam U   Deduced type of the value to insert (lvalue or rvalue ref).
    /// @param idx  Zero-based insertion index (before the element currently at @p idx).
    /// @param v    Forwarding reference to the value to insert.
    /// @return Iterator pointing to the newly inserted element.
    /// @complexity O(n).
    template<typename U>
    Iterator insert_at(usize idx, U&& v) {
        if (size_ == cap_) {
            usize nc = cap_ == 0 ? 4 : cap_ + (cap_ >> 1);
            T* nd = Alloc::allocate(nc);
            move_construct_range(nd, data_, idx);
            Alloc::construct(nd + idx, traits::forward<U>(v));
            move_construct_range(nd + idx + 1, data_ + idx, size_ - idx);
            Alloc::deallocate(data_, cap_);
            data_ = nd; cap_ = nc;
        } else {
            shift_right(data_ + idx, size_ - idx);
            Alloc::construct(data_ + idx, traits::forward<U>(v));
        }
        ++size_;
        return Iterator(data_ + idx);
    }
};

} // namespace dsc
